Renamed some variables

diff --git a/bin/functions b/bin/functions
--- a/bin/functions
+++ b/bin/functions
@@ -55,7 +55,7 @@ mysql_dump() {
   [ -n "$db_extra" ] && echo "db_extra: $db_extra"
   echo "other   : $@"
 
-  mysqldump -h "$DB_HOST" -u "$DB_USER" --password="$DB_PASSWORD" "$@" $db_extra "${_excluded_tables[@]}" "$DB_NAME" ${included_tables//,/ } > "$_module_cache/$dump_name.sql" || exit $?
+  mysqldump -h "$DB_HOST" -u "$DB_USER" --password="$DB_PASSWORD" "$@" $db_extra "${_excluded_tables[@]}" "$DB_NAME" ${included_tables//,/ } > "$module_cache/$dump_name.sql" || exit $?
 
   echo "END   mysql_dump"
 
@@ -83,10 +83,9 @@ backup_single_module() {
 }
 
 dupl() {
-  PASSPHRASE="$PASSPHRASE" FTP_PASSWORD="$FTP_PASSWORD" duplicity -v4 \
-  --gpg-options "--compress-algo=bzip2 --bzip2-compress-level=9" \
-  --archive-dir="$MBKP_ARCHIVE" \
-  --name "$module" "$@"
+  PASSPHRASE="$PASSPHRASE" FTP_PASSWORD="$FTP_PASSWORD" duplicity \
+  --archive-dir="$MBKP_ARCHIVE" --name "$module" --ssh-askpass $SSH_OPTS \
+  "$@"
 }
 
 do_backup() {
@@ -98,8 +97,9 @@ do_backup() {
   dupl remove-all-but-n-full "$keep_last_n_backups" --force "$backup_target"
   dupl cleanup --force "$backup_target" # --extra-clean
 
-  dupl --ssh-askpass $SSH_OPTS --asynchronous-upload ${volsize:+--volsize="$volsize"} \
-  --full-if-older-than $full_if_older_than $extra "${file_selection[@]}" \
+  dupl --gpg-options "--compress-algo=bzip2 --bzip2-compress-level=9" \
+  --asynchronous-upload ${volsize:+--volsize="$volsize"} \
+  --full-if-older-than $full_if_older_than $extra "${_file_selection[@]}" \
   "$backup_src" "$backup_target" || FAILED="$module"
 }
 
@@ -123,13 +123,13 @@ init() {
   ((VERBOSE)) && echo "Calling $mbkp_conf_file"
   . "$mbkp_conf_file" || exit 1
 
-  mbkp_conf_file="$MBKP_CONFIG/mbkp.conf"
+  mbkp_conf_file="$MBKP_CONFIG_BASE/mbkp.conf"
   [ -s "$mbkp_conf_file" ] && {
     ((VERBOSE)) && echo "Calling $mbkp_conf_file"
     . "$mbkp_conf_file" || exit 1
   }
 
-  local mbkp_priv_hook="$MBKP_CONFIG/priv/mbkp-priv.conf"
+  local mbkp_priv_hook="$MBKP_CONFIG_BASE/priv/mbkp-priv.conf"
   if [ -f "$mbkp_priv_hook" ]; then
     ((VERBOSE)) && echo "Calling $mbkp_priv_hook"
     . "$mbkp_priv_hook" || exit 1
@@ -142,16 +142,16 @@ init() {
     exit 1
   }
 
-  [ -d "$MBKP_MODULE_CACHE" ] || {
-    mkdir -p "$MBKP_MODULE_CACHE" || {
-      echo "Unable to create module cache at '$MBKP_MODULE_CACHE'."
+  [ -d "$MBKP_MODULE_CACHE_BASE" ] || {
+    mkdir -p "$MBKP_MODULE_CACHE_BASE" || {
+      echo "Unable to create module cache base dir at '$MBKP_MODULE_CACHE_BASE'."
       exit 2
     }
   }
 
-  [ -d "$MBKP_LOCAL_DATA" ] || {
-    mkdir -p "$MBKP_LOCAL_DATA" || {
-      echo "Unable to create local data dir at '$MBKP_LOCAL_DATA'."
+  [ -d "$MBKP_LOCAL_BACKUPS_BASE" ] || {
+    mkdir -p "$MBKP_LOCAL_BACKUPS_BASE" || {
+      echo "Unable to create local backups dir at '$MBKP_LOCAL_BACKUPS_BASE'."
       exit 3
     }
   }
@@ -174,8 +174,8 @@ init_module() {
   FAILED=''
 
   # Variables that can be overriden on module config files
-  _module_cache="$MBKP_MODULE_CACHE/$module"
-  mbkp_src="$_module_cache"
+  module_cache="$MBKP_MODULE_CACHE_BASE/$module"
+  mbkp_src="$module_cache"
   mbkp_target="$MBKP_BASE_TARGET"
   volsize="50"
   full_if_older_than="6M"
@@ -194,13 +194,13 @@ init_module() {
   excluded_tables=''
   db_extra=''
 
-  local module_hook="$MBKP_CONFIG/priv/$module.conf"
+  local module_hook="$MBKP_CONFIG_BASE/priv/$module.conf"
   [ -f "$module_hook" ] && {
     echo "Calling: $module_hook"
     . "$module_hook"
   }
 
-  module_hook="$MBKP_CONFIG/modules/$module.conf"
+  module_hook="$MBKP_CONFIG_BASE/modules/$module.conf"
   [ -f "$module_hook" ] && {
     echo "Calling: $module_hook"
     . "$module_hook"
@@ -212,9 +212,9 @@ init_module() {
 
   mbkp_full_target="$mbkp_target/$module"
 
-  [ -e "$_module_cache" ] || {
-    ((VERBOSE)) && echo "Creating $_module_cache"
-    mkdir "$_module_cache" || exit $?
+  [ -e "$module_cache" ] || {
+    ((VERBOSE)) && echo "Creating $module_cache"
+    mkdir "$module_cache" || exit $?
   }
 
   add_prefix "#!process_file_list_item" file_list
@@ -225,20 +225,20 @@ init_module() {
   add_prefix "$mbkp_src" 1 excluded_files
   add_prefix "--exclude" 0 excluded_files "${excluded_files[@]}"
 
-  include_gfilelist="$MBKP_CONFIG/modules/$module.files"
+  include_gfilelist="$MBKP_CONFIG_BASE/modules/$module.files"
   [ -s "$include_gfilelist" ] && {
     include_gfilelist="--include-globbing-filelist $include_gfilelist"
   } || include_gfilelist=''
 
-  exclude_gfilelist="$MBKP_CONFIG/modules/$module.excludes"
+  exclude_gfilelist="$MBKP_CONFIG_BASE/modules/$module.excludes"
   [ -s "$exclude_gfilelist" ] && {
     exclude_gfilelist="--exclude-globbing-filelist $exclude_gfilelist"
   } || exclude_gfilelist=''
 
   set -f
-  file_selection=(--exclude-if-present CACHEDIR.TAG ${file_list[@]})
-  ((excludes_first)) && file_selection+=("${excluded_files[@]}" "${included_files[@]}") || file_selection+=("${included_files[@]}" "${excluded_files[@]}")
-  file_selection+=($include_gfilelist $exclude_gfilelist)
+  _file_selection=(--exclude-if-present CACHEDIR.TAG ${file_list[@]})
+  ((excludes_first)) && _file_selection+=("${excluded_files[@]}" "${included_files[@]}") || _file_selection+=("${included_files[@]}" "${excluded_files[@]}")
+  _file_selection+=($include_gfilelist $exclude_gfilelist)
 
   echo "Module source: $mbkp_src"
   echo "Module target: $mbkp_full_target"
@@ -258,10 +258,10 @@ init_module() {
 
 pre_module_backup() {
 
-  local pre_hook="$MBKP_CONFIG/modules/$module.pre"
+  local pre_hook="$MBKP_CONFIG_BASE/modules/$module.pre"
   if [ -s "$pre_hook" ]; then
     echo "Calling: $pre_hook"
-    . $pre_hook "$_module_cache" || exit $?
+    . $pre_hook "$module_cache" || exit $?
   else
     ((VERBOSE)) && echo "### NOT CALLED: $pre_hook"
   fi
@@ -272,10 +272,10 @@ pre_module_backup() {
 
 post_module_backup() {
 
-  local post_hook="$MBKP_CONFIG/modules/$module.post"
+  local post_hook="$MBKP_CONFIG_BASE/modules/$module.post"
   if [ -s "$post_hook" ]; then
     echo "Calling: $post_hook"
-   . $post_hook "$_module_cache" || FAILED="$post_hook"
+   . $post_hook "$module_cache" || FAILED="$post_hook"
   else
     ((VERBOSE)) && echo "### $post_hook NOT CALLED."
   fi
